# action.yml
name: 'PR review by ChatGPT'
description: 'Automating code review using ChatGPT with Github Actions integration on PRs.'
inputs:
  openai_api_key: # id of input
    description: 'OpenAI API Key'
    required: true
    default: ''
  github_token: # id of input
    description: 'Github API Key'
    required: true
    default: ''
  github_pr_id: # id of input
    description: 'Github PR ID'
    required: true
    default: ''
  openai_engine: # id of input
    description: 'Choose the GPT model for code review. Options: gpt-4, gpt-3.5-turbo, gpt-3.5-turbo-16k, text-davinci-002, text-babbage-001, text-curie-001, text-ada-001'
    required: false
    default: 'gpt-3.5-turbo-16k'
  openai_temperature: # id of input
    description: 'What sampling temperature to use. Higher values means the model will take more risks. Try 0.9 for more creative applications, and 0 (argmax sampling) for ones with a well-defined answer.'
    required: false
    default: '0.5'
  openai_max_tokens: # id of input
    description: 'The maximum number of tokens to generate in the completion.'
    required: false
    default: '16384'
  mode: # id of input
    description: 'How to capture PR changes. Options: files, patch'
    required: false
    default: 'files'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.openai_api_key }}
    - ${{ inputs.github_token }}
    - ${{ inputs.github_pr_id }}
    - ${{ inputs.openai_engine }}
    - ${{ inputs.openai_temperature }}
    - ${{ inputs.openai_max_tokens }}
    - ${{ inputs.mode }}
